/*
 Copyright (c) Admeta AB 2008-2016
 Version 1.85.0
*/
function admetaEval(C){return eval(C)}void 0===window.Admeta||Admeta.isFn||(window.legacyTags=Admeta.aTags,window.legacyll=Admeta.ll,Admeta=void 0);
var Admeta=Admeta||function(){function C(a){return-1!==a.indexOf("/",a.length-1)?a:a+"/"}function D(){return Math.floor(1E8*Math.random())}function da(a){var b;try{if(a)for(b=0;b<a.length;b++)if(a[b]===ea)return!0}catch(c){}return!1}function L(){return da(Ka)?!0:window.AdmetaLogging}function O(a){var b;return void 0!==window.ADM_PL&&void 0!==window.ADM_PL.pbId&&a===P&&(b=parseInt(ADM_PL.pbId),0<b)?C(G+"p"+b+"."+I):a}function fa(){M=C(window.AdmetaScriptBase||G+"s."+I);var a=-1!==M.indexOf("localhost")?
"":"script/";ga=C(window.AdmetaFrontBase||P);Q=M+"IfrJSAdLoader.htm?HTML=1&cb={cb}";Admeta.base=O(ga);Admeta.textAdsJS=M+a+"TextAds.js?{sv}"}function w(){if(window.disableIframeCheck)return m.NoIframe;try{if(top.location.href&&window.self!==window.top)return m.SameDomainIframe}catch(a){return m.CrossDomainIframe}return m.NoIframe}function ha(){try{return!ia&&"1"===localStorage.getItem("AdmetaLogger")}catch(a){}return!1}function ja(a,b){try{if(ha()){var c=new CustomEvent("AdmetaLogger",{detail:{logCode:a,
data:b}});w()===m.CrossDomainIframe?document.dispatchEvent(c):top.document.dispatchEvent(c);return!0}}catch(d){}return!1}function z(a){try{ja(a,Array.prototype.slice.call(arguments,1))||0===z.toString().indexOf("function logDebug")&&console.info(arguments)}catch(b){}}function ka(a){return"http://p.admeta.se/pixel.gif?v="+Admeta.fullVersion+"&"+a+"&cb="+D()}function A(a){if(L())try{Admeta.loadImg(ka(a))}catch(b){}}function la(a){try{Admeta.loadImg("http://p.admeta.se/error.gif?e="+encodeURIComponent(a)+
"&cb="+D())}catch(b){}}function R(a,b){z(p.Undef,"Exception: ",a,b);if(L()){var c="";try{c=Admeta.fullVersion,c+=": "+a.toString()}catch(d){}try{c+=": ",c+=JSON.stringify(a.stack)}catch(d){}try{b&&(c+=": ",c+=JSON.stringify(b))}catch(d){}try{c=c.substr(0,3500)}catch(d){}la(c)}}function ma(){Admeta.focus=1}function na(){Admeta.focus=0}function S(){return(void 0===ADM_PL.pId?escape(ADM_PL.page).replace(/%/g,"_")+ADM_PL.width+ADM_PL.height:ADM_PL.pId)+":"+(void 0===ADM_PL.rank?1:ADM_PL.rank)+":"+(16777216*
(1+Math.random())|0).toString(16).substring(1)}function oa(){var a=Admeta.Text;a.forceSize=ADM_PL.textSize;a.forceCenterImg=ADM_PL.centerImages;a.forceBaseFontSize=ADM_PL.fontSize;a.forceBaseFont=ADM_PL.font;ADM_PL.TextSize=void 0;ADM_PL.CenterImages=void 0;ADM_PL.fontSize=void 0;ADM_PL.font=void 0}function pa(a){return-1!==a.indexOf("&")||-1!==a.indexOf("?")?escape(a):a}function T(a){var b=document.cookie,c=b.indexOf(a+"=");if(-1===c)return"";c+=a.length+1;a=b.indexOf(";",c);-1===a&&(a=b.length);
return decodeURIComponent(b.substring(c,a))}function La(a){var b="",c=w();(function(){function b(a){try{return a=a.replace(/^\s+|\s+$/gm,""),""===a||"$"===a.slice(0,1)||"{"===a.slice(0,1)?void 0:a}catch(c){}}a&&void 0!==a.referrer&&(a.referrer=b(a.referrer));a&&void 0!==a.referrerBackup&&(a.referrerBackup=b(a.referrerBackup))})(a);if(a&&void 0!==a.referrer)b=a.referrer;else if(a&&void 0!==a.referrerBackup&&c===m.CrossDomainIframe)b=a.referrerBackup;else if(c===m.CrossDomainIframe)b=document.referrer;
else if(c===m.SameDomainIframe)try{b=top.location.href}catch(d){}return encodeURIComponent(b)}function qa(a){var b=0,c="",d,e=!1,g;try{if(void 0!==a.wlrcmd)b=1,c=a.wlrcmd;else if(void 0!==a.adptpecresp&&""!==a.adptpecresp)b=2,c=a.adptpecresp;else if(void 0!==a.adptkwresp&&""!==a.adptkwresp)b=2,c=a.adptkwresp;else if(void 0!==a.adt_bt)b=2,c=a.adt_bt;else if(void 0!==a.W2T_UserCategories)b=3,c=a.W2T_UserCategories.join(",");else if(void 0!==a.rsinetsegs)b=3,c=a.rsinetsegs.join(",");else if(void 0!==
a.nuggprof&&""!==a.nuggprof)b=2,c=a.nuggprof;else if(void 0!==a.ADTOTAL_PDP||void 0!==a.ADTOTAL_PDG){var f="",h;try{void 0!==a.ADTOTAL_PDP&&(f=a.ADTOTAL_PDP.substring(0,3)+";",h=parseInt(a.ADTOTAL_PDP.substring(4,6),10),19>=h?f+="AGE1":29>=h?f+="AGE2":39>=h?f+="AGE3":49>=h?f+="AGE4":59>=h?f+="AGE5":60<=h&&(f+="AGE6"),f+=";"),void 0!==a.ADTOTAL_PDG&&(f+=a.ADTOTAL_PDG.replace(/,/g,"="))}catch(k){}c=f;""!==c&&(b=2)}else if(void 0!==a.onet_wl&&""!==a.onet_wl)b=1,c=a.onet_wl;else if(void 0!==a.ccauds){b=
2;h="";try{for(f=0;f<a.ccauds.Profile.Audiences.Audience.length;f++)0<f&&(h+=";"),h+=a.ccauds.Profile.Audiences.Audience[f].abbr}catch(k){}c=h;e=!0}window.localStorage&&void 0!==window.localStorage.kxmktadapt_segs&&""!==window.localStorage.kxmktadapt_segs&&(g=window.localStorage.kxmktadapt_segs,e?(2===b&&(c=c.replace(/;/g,",")),c=c+","+g):c=g,b=3);0===b&&(d=T("pec_resp"),""!==d&&(b=2,c=d.replace(/,/g,";")),d=T("rsi_segs"),""!==d&&(b=3,c=d.replace(/\|/g,",")),d=T("adptseg"),""!==d&&(b=2,c=d.replace(/([\w,]+)-([\w]+)/g,
"$2=$1").replace(/,/g,":").replace(/#/g,";")));if(0===b){var l,c=(l=document.cookie.match(/frosmo_keywords=([^;$]+)/))?l[1].replace(/\./g,","):"";""!==c&&(b=3)}}catch(k){}return{vitp:b,vit:c}}function F(a,b,c){for(;-1!==a.indexOf(b);)a=a.replace(b,c);return a}function ra(a){a=F(a,"{timestamp}",(new Date).getTime());a=F(a,"{timediff}",sa);return F(a,"{random}",D())}function Ma(a){if(a){if(a.deviceId)return a.deviceId;if(a.userId)return a.userId}}function U(a,b){var c;c=b&&b.segments?{vitp:3,vit:b.segments}:
void 0;if(!c&&(c=qa(window),0===c.vitp&&w()===m.SameDomainIframe))try{c=qa(window.parent)}catch(d){}return Admeta.setParams(a,[["arp",0],["jsv",Admeta.version],["tsv",Admeta.textVersion],["cts",(new Date).getTime()],["fl",Admeta.Flash.support()?1:0],["url",La(b)],["fp",ta.get()],["mpp",V],["uid",encodeURIComponent(Ma(b)||"")],["jscb",b&&void 0!==b.jsonCallback?b.jsonCallback:""],["pbId",b?b.pbId||"":""],["clk",b&&void 0!==b.clk?pa(b.clk):""],["oid",b?encodeURIComponent(b.orderid||""):""],["mraid",
b?encodeURIComponent(b.mraid||""):""],["apid",b?encodeURIComponent(b.appId||""):""],["apbndl",b?encodeURIComponent(b.appBundle||""):""],["cb",D()],["vitp",c.vitp],["vit",escape(c.vit)]])}function ua(a){void 0===Admeta.xRenderF&&(Admeta.xRenderF={});if(ADM_PL.renderF||ADM_PL.ADM_RENDERF){var b=ADM_PL.renderF?ADM_PL.renderF:ADM_PL.ADM_RENDERF;Admeta.xRenderF[a]=b;Admeta.xRenderF[ADM_PL.pId]=b}}function W(){var a="site page width height rank referrer referrerBackup subPublisher orderid ecpm atf tagId mraid mraid nativeAd nativeLayout appId appBundle clk adserverid deviceId userId segments".split(" "),
b,c=window.ADM_PL;if(c){for(b=0;b<a.length;b++)a:{var d=c,e=a[b],g=void 0;for(g in d)if(d.hasOwnProperty(g)&&g.toLowerCase()===e.toLowerCase()){d[e]=d[g];break a}}c.ATpagefilter&&(c.page="Default web page");void 0!==c.pkg&&(c.pkg=encodeURIComponent("pkg|"+decodeURIComponent(c.pkg)));c.nativeLayout&&(c.nativeAd=1)}}function va(a){Admeta.MatC.setup(ADM_PL.pId,ADM_PL.rank,-1,a,void 0,ADM_PL.refresh,(ADM_PL.fade?1:0)|(ADM_PL.attRefreshed?2:0),ADM_PL.width,ADM_PL.height,void 0,ADM_PL.brandImgUrl,ADM_PL.brandLandingUrl,
ADM_PL.brandImgHeight,ADM_PL.brandImgPos,ADM_PL.unsoldTag,ADM_PL.unsoldMethod,ADM_PL.iframedUnsold,ADM_PL.protect,ADM_PL.embed,ADM_PL.soldMethod)}function wa(a,b,c,d,e){var g=!1;if(void 0!==e)return e?1:0;if(void 0===b||void 0===c||void 0===a)return 0;!document.getElementById(a)&&d&&(document.write("<div id='"+a+"'></div>"),g=!0);d=document.getElementById(a);a=Admeta.MatC.checkElemForcedAreaVisible(a,b,c);try{g&&d.parentNode&&d.parentNode.removeChild(d)}catch(f){}return a?1001:0}function xa(a,b){return Admeta.setParams(a,
[["wsName",encodeURIComponent(decodeURIComponent(b.site))],["wName",encodeURIComponent(decodeURIComponent(b.page))],["width",b.width],["height",b.height],["subp",b.subPublisher?encodeURIComponent(decodeURIComponent(b.subPublisher)):""]])}function ya(a,b,c,d){return Admeta.setParams(a,[["rank",b.rank],["pp",b.pkg||""],["ecpm",b.ecpm||""],["ntv",b.nativeAd||""],["ntl",b.nativeLayout||""],["adsid",encodeURIComponent(decodeURIComponent(b.adserverid||""))],["rpos",d],["gid",c]])}function Na(a){function b(a){return void 0!==
a.pId?a.pId+"":a.site+":"+a.page+":"+a.width+":"+a.height}function c(){var b,c=-1;for(b=0;b<a.length;b++)(-1===c||a[b].admpl.rank<c)&&!a[b].touched&&(c=a[b].admpl.rank);return c}function d(g){if(-1!==g){var f={},h;for(e=0;e<a.length;e++)if(h=b(a[e].admpl),a[e].admpl.rank===g){if(void 0===f[h])f[h]=!0;else{h=a[e].admpl;for(var l=b(a[e].admpl),k=0,q=1,r=void 0;k<a.length;)r=a[k].admpl,b(r)===l&&r.rank===q?(q++,k=0):k++;h.rank=q}a[e].touched=!0}d(c())}}var e;d(c());return a}function J(a){for(var b;Admeta.pushedAds&&
0<Admeta.pushedAds.length;){var c=void 0;b=[];var d=0;if(void 0===Admeta.pushedAds||0===Admeta.pushedAds.length)b=[];else for(c=Admeta.pushedAds[0].admpl.pbId;d<Admeta.pushedAds.length;)Admeta.pushedAds[d].admpl.pbId==c?b.push(Admeta.pushedAds.splice(d,1)[0]):(d+=1,V=1);a:{var c=a,d=[],e=void 0,g=void 0,f=void 0,h=void 0,l=void 0,k=void 0;if(void 0===b||0===b.length)A("e=processFullPageNoAds");else{b=Na(b);for(e=0;e<b.length;e++)c&&!document.getElementById(b[e].gid)||d.push(e);window.ADM_PL=window.ADM_PL||
{};oa();b.length!==d.length&&A("e=tagsNotFound&pas="+b.length+"&up="+d.length);if(0<d.length){g=Admeta.setParams(Admeta.base+"JSAdservingMP.ashx?pc={pc}&pbId={pbId}&clk={clk}&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&arp={arp}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&url={url}&fp={fp}&oid={oid}&exr={exr}&mraid={mraid}&apid={apid}&apbndl={apbndl}&mpp={mpp}&uid={uid}&cb={cb}",[["pc",d.length]]);k=b[d[0]].admpl;window.ADM_PL.orderid=k.orderid||window.ADM_PL.orderid;window.ADM_PL.referrer=k.referrer||
window.ADM_PL.referrer;window.ADM_PL.mraid=k.mraid||window.ADM_PL.mraid;window.ADM_PL.appId=k.appId||window.ADM_PL.appId;window.ADM_PL.appBundle=k.appBundle||window.ADM_PL.appBundle;window.ADM_PL.pbId=k.pbId||window.ADM_PL.pbId;window.ADM_PL.jsonCallback=k.jsonCallback||window.ADM_PL.jsonCallback;g=U(g,ADM_PL);for(e=0;e<d.length;e++){f=b[d[e]];k=f.admpl;l=wa(f.gid,k.width,k.height,!1,k.atf);if(void 0!==k.pId)h=Admeta.setParams("&pId{o}={pId}&rank{o}={rank}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",
[["o",e]]),h=Admeta.setParams(h,[["wId",k.wId],["pId",k.pId]]);else if(void 0!==k.pbId&&void 0!==k.site&&void 0!==k.page&&void 0!==k.width&&void 0!==k.height)h=Admeta.setParams("&wsName{o}={wsName}&wName{o}={wName}&rank{o}={rank}&bfDim{o}={width}x{height}&subp{o}={subp}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",[["o",e]]),h=xa(h,k);else{A("e=invalidTagMP&admpl="+encodeURIComponent(JSON.stringify(k)));break a}h=ya(h,k,f.gid,l);h=
Admeta.setParams(h,[["clk",pa(k.clk||"")]]);g+=h}z(p.ExecMultipleRequest,b,g);Admeta.inFrontCall=!0;Admeta.Script.load(g,ADM_PL.defLoad,void 0,1)}}}}}function Oa(a){var b,c={};for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function H(a){W();va(a);ua(a);void 0===Admeta.pushedAds&&(Admeta.pushedAds=[]);Admeta.pushedAds.push({gid:a,admpl:Oa(window.ADM_PL)})}function X(){var a=void 0!==window.ADM_PL.tagId?window.ADM_PL.tagId:S();document.write('<div id="'+a+'"></div>');H(a);ADM_PL.wId=void 0;ADM_PL.pId=
void 0;ADM_PL.site=void 0}function za(){ADM_PL.tagId&&"sp"===ADM_PL.tp&&document.getElementById(ADM_PL.tagId)&&(z(p.Undef,"Corrected tag sp->spt",ADM_PL.tagId),ADM_PL.tp="spt")}function Aa(){ADM_PL.async&&(ADM_PL.defLoad=ADM_PL.async);Admeta.defLoad=void 0===ADM_PL.defLoad||Admeta.defLoad?Admeta.defLoad:ADM_PL.defLoad;"sp"===ADM_PL.tp&&Admeta.defLoad&&(ADM_PL.tp="spp");za();var a;a:{var b=ADM_PL.tp;if("sp"===b||"fp"===b||"spp"===b)try{if(document.currentScript&&document.currentScript.async){a=!1;
break a}}catch(d){}a=!0}if(a){Admeta.base=O(Admeta.base);z(p.ReceiveRequest,ADM_PL);switch(ADM_PL.tp){case "sp":a:{a=S();var b=Admeta.base,c;va(a);ua(a);oa();c=wa(a,ADM_PL.width,ADM_PL.height,!0,ADM_PL.atf);if(void 0!==ADM_PL.pId)b=Admeta.setParams(b+"JSAdservingSP.ashx?wId={wId}&pId={pId}&rank={rank}&gid={gid}&clk={clk}&di=1&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&pp={pp}&url={url}&fp={fp}&rpos={rpos}&oid={oid}&ecpm={ecpm}&exr={exr}&ntv={ntv}&mraid={mraid}&ntl={ntl}&apid={apid}&apbndl={apbndl}&mpp={mpp}&adsid={adsid}&uid={uid}&cb={cb}",
[["wId",ADM_PL.wId],["pId",ADM_PL.pId]]);else if(void 0!==ADM_PL.pbId&&void 0!==ADM_PL.site&&void 0!==ADM_PL.page&&void 0!==ADM_PL.width&&void 0!==ADM_PL.height)b+="JSAdservingSP.ashx?pbId={pbId}&wsName={wsName}&wName={wName}&rank={rank}&bfDim={width}x{height}&subp={subp}&gid={gid}&clk={clk}&di=1&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&pp={pp}&url={url}&fp={fp}&rpos={rpos}&oid={oid}&ecpm={ecpm}&exr={exr}&ntv={ntv}&mraid={mraid}&ntl={ntl}&apid={apid}&apbndl={apbndl}&mpp={mpp}&adsid={adsid}&uid={uid}&cb={cb}",
b=xa(b,ADM_PL);else{A("e=invalidTagSP&admpl="+encodeURIComponent(JSON.stringify(ADM_PL)));break a}b=ya(b,ADM_PL,a,c);b=U(b,ADM_PL);z(p.ExecSingleRequest,{gid:a},ADM_PL,b);ADM_PL.wId=void 0;ADM_PL.pId=void 0;ADM_PL.site=void 0;ADM_PL.defLoad=void 0;Admeta.inFrontCall=!0;Admeta.Script.load(b,Admeta.defLoad,void 0,1)}break;case "fp":X();break;case "fpt":H(ADM_PL.tagId);ADM_PL.wId=void 0;ADM_PL.pId=void 0;ADM_PL.site=void 0;break;case "fpc":J(!0);break;case "spt":H(ADM_PL.tagId);J(!0);break;case "spp":X();
J(!0);break;default:la("Unrecognized ADM_PL.tp: "+ADM_PL.tp)}window.ADM_PL=void 0}else z(p.Undef,"Test write failed!",ADM_PL)}function Y(a,b){return Admeta.setParams(a,[["id",b.innerId],["width",b.w],["height",b.h]])}function Ba(a){a&&a.RF&&Admeta.Refresh.attMaterial(a);if(void 0!==a.soldMethod){var b=a.soldMethod,b=Y(b,a);a=Admeta.setParams(b,[["adid",a.adId]]);admetaEval(a)}}function Ca(a,b){for(var c=a.length;c--;)if(a[c]===b)return!0;return!1}function Da(a){try{if(a.contentDocument)return a.contentDocument;
if(a.contentWindow)return a.contentWindow.document;if(window.frames[a.name])return window.frames[a.name].document}catch(b){}}function Ea(a,b,c,d,e){b||(b=0);a.SIV=b;a.w=void 0!==d?d:a.w;a.h=void 0!==e?e:a.h;a.visitorState=c;Admeta.SIV.setup(a)}function Z(a,b){var c=document.getElementById(a),d=Admeta.getBrowser(),e=d[0],d=d[1],g,f,h;h=function(a){(g=Da(c))?(f="msie"===e||"opera"===e,g.open(),f&&1===a&&g.close(),g.write(Admeta.embedIfrCode(b)),f||g.close()):A("e=SameDomainIframeFail")};if(Admeta.isVisible(c)||
"complete"===document.readyState||"complete"===c.readyState)h(1);else switch(e){case "chrome":case "safari":c.onload=function(){c.onload=void 0;h()};break;case "msie":if(8>=d){c.attachEvent("onload",function k(){c.detachEvent("onload",k);h()});break}default:c.onload=h}}function Fa(a,b){var c,d=w(),e,g;try{if(a.highlight){c=document.getElementById(a.innerId);e="("+a.w+"x"+a.h+") pId: "+a.pid+(b?" unsold":" adId: "+a.adId)+" gid: '"+a.innerId+"'"+(d===m.SameDomainIframe?" Iframe same domain":d===m.CrossDomainIframe?
"Iframe cross domain":"");c.style.border="dashed 2px red";c.style.position="relative";var f=document.createElement("div");f.style.position="absolute";f.style.backgroundColor="#FFF";f.style.color="#000";f.style.left=0;f.style.top=0;f.style.font="14px Arial";f.style.textAlign="left";f.style.borderBottom="solid 1px red";f.style.padding="5px";f.style.zIndex=2147483647;f.innerHTML=e;c.appendChild(f)}g=d===m.SameDomainIframe?window.frameElement.id:a.innerId;ja(p.AdPosition,{pInfo:a,targetId:g,unsold:b,
ifrType:d})}catch(h){console.info(h)}}function aa(a){function b(){e+=1;10<e||setTimeout(function(){c.offsetWidth>2*a.adChoicesWidth?d.style.display="":b()},1E3)}var c,d,e=0;if(void 0!==a.adChoicesIdCollapsed&&(c=document.getElementById(a.innerId))&&(d=document.getElementById(a.adChoicesIdCollapsed))){try{if(c.parentNode.hasAttribute&&c.parentNode.hasAttribute("data-am")||void 0!==c.parentNode.attributes("data-am")){d.style.display="none";return}}catch(g){}c.offsetWidth<=2*a.adChoicesWidth&&(d.style.display=
"none");b()}}function ba(a,b){var c;var d=Admeta.MatC.getExisting(a.gid),e=a.sImg,g=a.sImgUrl,f=a.imgH;c=a.sPos;d&&void 0!==d.sImg&&(e=0===d.sImg?void 0:d.sImg,g=d.sImgUrl,f=d.imgH||0,c=d.sPos);void 0===e?c=void 0:(d="right:0px;bottom:0px",1===c&&(d="left:0px;bottom:0px"),2===c&&(d="left:0px;top:0px"),3===c&&(d="right:0px;top:0px"),c={h:f,pad:2<=c?"padding-top:"+f:"",html:"<a style='position:absolute;"+d+";z-index:100;border:0;padding:0;margin:0;width:auto;font-size:0' href='"+g+"' target='_blank' rel='nofollow'><img style='border:0;margin:0;padding:0' src='"+
e+"'></img></a>"});e=Admeta.AdChoices.getCode(a);f=g="";if(!(a.SIV||a.RF||a.embed||c)&&""===e)return b;(a.RF||a.SIV)&&a.gid===a.innerId&&Admeta.MatC.setInnerId(a);c&&(g=c.pad,f=c.html);c=a.innerId;null!==document.getElementById(a.innerId)&&(c+="_mbd");return b=a.embed?"<div data-am id='"+c+"' style='position:relative;width:"+a.w+"px;height:"+a.h+"px'>"+e+b+f+"</div>":"<fieldset data-am id='"+c+"' style='position:relative;display:inline;border:0;margin:0;padding:0;"+g+"'>"+e+b+f+"</fieldset>"}function K(a,
b,c,d,e,g){var f=Admeta.debug?"border: solid 2px"+(c?" red":" green"):"border-style:none;";return"<iframe data-am"+(void 0!==b||c?" name='"+(c?"ADM:"+escape(c):a)+"'":"")+" id='"+a+"' scrolling='no' frameborder='0' marginwidth=0 marginheight=0 hidefocus='true' style='margin:0px;width:"+d+"px;height:"+e+"px;"+f+"' src='about:blank'"+(void 0!==g?" mId='"+g+"'":"")+"></iframe>"}function Ga(a,b,c){var d=Admeta.MatC.getExisting(a);void 0===d&&(d=Admeta.MatC.setup(1,1,-1,a,0,0,0,b,c,0,void 0,void 0,0,0,
void 0,void 0,0,0,0,void 0),d.incomplete=1);return d}function N(a,b){var c=(""+b).split(","),d;for(d=0;d<c.length;d++)Ca(a,c[d])||a.push(c[d])}function Ha(a,b){if(void 0!==b){var c=(""+b).split(","),d;for(d=0;d<c.length;d++)Ca(a,c[d])||a.push(c[d])}}function Ia(a){var b,c,d,e,g,f,h="",l,k,q;try{b=a.pbId||"",c=a.pId||"",d=a.site||"",e=a.page||"",g=a.width||"",f=a.height||"",l=a.tp||"",k=w(),q=JSON.stringify(a),h="&pbId="+encodeURIComponent(b)+"&pId="+encodeURIComponent(c)+"&site="+encodeURIComponent(d)+
"&page="+encodeURIComponent(e)+"&w="+encodeURIComponent(g)+"&h="+encodeURIComponent(f)+"&tp="+encodeURIComponent(l)+"&ifr="+k+"&admpl="+encodeURIComponent(q)}catch(r){}return h}var I="atemda.com",G=window.AdmetaProtocol||"//",P=C(G+I),M,ga,Q,Ja=!1,ta,m={NoIframe:0,SameDomainIframe:1,CrossDomainIframe:2},p={Undef:0,ReceiveRequest:1,ReceiveRequestInFriendlyIframe:2,ExecSingleRequest:3,ExecMultipleRequest:4,WritingMaterial:5,InsertMaterial:6,Unsold:7,AdPosition:8},ea,Ka=[],Pa=[235,251],sa=0,V=0,ia=!1;
ta=function(){var a;return{get:function(){if(void 0!==a)return a;try{return a="0;"+screen.width.toString(16)+";"+screen.height.toString(16)+";"+screen.colorDepth.toString(16)}catch(b){}return""}}}();return{isFn:!0,aTags:window.legacyTags,ll:window.legacyll,version:"1.85",fullVersion:"1.85.0",textVersion:"2.26",focus:1,protect:!1,debug:!1,setTest:function(a){I=a;Admeta.base=P=C(G+I);V=!1;ia=!0},init:function(a,b,c){sa=(new Date).getTime()-c;A("e=admetaInit");this.protect=void 0===b?this.protect:b;
Ja||(this.SIV.init(a),window.addEventListener?(window.addEventListener("focus",ma,!1),window.addEventListener("blur",na,!1)):window.attachEvent&&(window.attachEvent("onfocus",ma),window.attachEvent("onblur",na)),Ja=!0)},loadImg:function(a){Admeta.imgLoad=Admeta.imgLoad||[];var b=new Image(0,0);b.src=a;Admeta.imgLoad.push(b)},embedInFieldSet:function(a,b,c,d,e){return"<fieldset id='"+a+"' style='display:inline;border:0;margin:0;overflow:hidden;padding:0;"+d+(b?"width:"+b+"px;":"")+(c?"height:"+c+"px;":
"")+"position:relative;'>"+e+"</fieldset>"},isVisible:function(a){do{if(!a||"none"===a.style.display)return!1;a=a.parentNode}while(a&&"BODY"!==a.tagName);return!0},iframedCode:function(a,b,c,d,e){-1!==b.search(/<script/i)||e?(e=document.createElement("iframe"),e.width=c,e.height=d,e.scrolling="no",e.frameBorder=0,e.hideFocus=0,e.style.borderStyle="none",e.style.margin=0,document.getElementById(a).appendChild(e),a=Da(e),a.open(),a.write(this.embedIfrCode(b)),a.close()):document.getElementById(a).innerHTML=
b},loadAdsJSON:function(a,b){for(var c,d=window.ADM_PL,e;0<b.length;)window.ADM_PL=b.pop(),W(),c=void 0!==window.ADM_PL.tagId?window.ADM_PL.tagId:S(),void 0!==window.ADM_PL.pbId&&(e=window.ADM_PL.pbId),H(c);window.ADM_PL={jsonCallback:a,pbId:e,defLoad:!0};fa();J(!1);window.ADM_PL=d},storeJSONMaterials:function(a){var b;for(b=0;b<a.Ids.length;b++)this.storeMaterial(a.Ids[b])},processATags:function(a){if(a&&0!==a.length){for(var b=window.ADM_PL,c=this.defLoad;0<a.length;)window.ADM_PL=a.pop(),ADM_PL===
b&&(b=void 0),H(ADM_PL.tagId);window.ADM_PL={tp:"fpc",async:!0};Aa();this.defLoad=c;window.ADM_PL=b}},processAsync:function(){this.inFrontCall||(window._Admeta&&this.processATags(window._Admeta.aTags),this.processATags(this.aTags))},logCall:function(){L()&&A("e=AdmetaJsLoaded"+Ia(ADM_PL))},processImpressions:function(){W();try{window.ADM_PL.pbId&&(ea=window.ADM_PL.pbId)}catch(c){}var a=window.ADM_PL;try{if(this.logCall(),fa(),this.Dispatcher.init(),this.Dispatcher.delayImpression())A("e=delayImpression"+
Ia(ADM_PL));else{void 0!==window.AdmetaIframed&&(this.adsServed=parent.Admeta.adsServed);var b=this.loadList||this.ll;if(b){for(;0<b.length;)b.pop()();this.ll?this.ll=[]:this.loadList=[]}this.processAsync();window.ADM_PL&&Aa()}}catch(c){R(c,a)}},outputMaterial:function(a,b,c,d,e,g){var f=this.getBrowser(),h,f=(b.embed||!1)&&g&&"msie"===f[0]&&9>=f[1],f=(g=b.protect||d||1!==a&&g||f)&&(b.protect||void 0===c);L()&&(c="<img src='"+ka("e=markupPixel&mat="+encodeURIComponent(JSON.stringify(b)))+"'></img>\n"+
c);g?(h="AMIfr_"+b.pid+"_"+b.o+"_"+b.adId+"_"+Admeta.MatC.generateId(),d=K(h,h,f?c:void 0,b.w,b.h,b.adId)):d=c;d=ba(b,d);z(1===a?p.WritingMaterial:p.InsertMaterial,b,c);if(1===a)document.write(d);else{a:if(a=document.getElementById(b.innerId),!a){if(void 0!==b.gid&&(a=document.getElementById(b.gid)))break a;a=document.getElementById("Admeta"+b.pid+"_"+b.o)}if(!a)throw"Element '"+b.innerId+(b.gid!==b.innerId?"' or '"+b.gid:"")+"' not found.";a.innerHTML=d}g&&(f?(c=void 0===e?Q:e,document.getElementById(h).src=
c.replace("{cb}",D())):Z(h,c));Fa(b,!1);Ba(b);aa(b);return h},insertMaterial:function(a,b,c){this.outputMaterial(0,a,b,c||!1,void 0,!1)},writeMaterial:function(a,b,c){this.outputMaterial(1,a,b,c||!1,void 0,!1)},customRendered:function(a){Ba(a)},setParams:function(a,b){var c;for(c=0;c<b.length;c++){var d=b[c][1],e=new RegExp("{"+b[c][0]+"}","g");!0===d&&(d=1);!1===d&&(d=0);a=a.replace(e,d)}return a},storeMaterial:function(a){void 0===this.adsServed&&(this.adsServed=[]);N(this.adsServed,a);try{w()===
m.SameDomainIframe&&(top.Admeta=top.Admeta||{},top.Admeta.adsServed=top.Admeta.adsServed||[],N(top.Admeta.adsServed,a))}catch(b){}},storeRtbAdvertiser:function(a){void 0===this.rtbAdvertisersServed&&(this.rtbAdvertisersServed=[]);Ha(this.rtbAdvertisersServed,a);try{w()===m.SameDomainIframe&&Ha(top.Admeta.rtbAdvertisersServed,a)}catch(b){}},setupMaterial:function(a,b,c,d,e,g,f,h,l,k,q,r,y,t,B,u){this.storeMaterial(c);this.storeRtbAdvertiser(u);a=this.MatC.setup(a,b,c,d,e,g,f,h,l,t,k,q,r,y,void 0,void 0,
void 0,B,void 0,void 0,u);this.SIV.setup(a);this.Refresh.setup(a);return a},versionFile:function(a,b){return this.setParams(a,[["sv",b]])},loadScript:function(a,b,c,d){var e=void 0===b?0:b,g;b=a;g="http:/"===b.slice(0,6)||"https:/"===b.slice(0,7)||"//"===b.slice(0,2);a=ra(a);b=g&&0===c?"<script type='text/javascript' src='"+a+"'>\x3c/script>":g&&1===c?"<img src='"+a+"' width='0px' height='0px'></img>":a;d?(c=e?1:0,a=Admeta.MatC.generateId(),b=K(a,a,b,0,0,void 0),1===c?document.write(b):document.body&&
(c=document.createElement("div"),c.innerHTML=b,document.body.appendChild(c)),b=Q,document.getElementById(a).src=b.replace("{cb}",D())):g&&0===c&&!e?this.Script.loadInTag(a):g&&1===c?this.loadImg(a):e?document.write(b):document.body&&(c=Admeta.MatC.generateId(),d=K(c,void 0,void 0,1,1,0),a=document.createElement("div"),a.innerHTML=d,document.body.appendChild(a),Z(c,b))},callUserScript:function(a,b,c){this.loadScript(a,b,1,c)},userMatch:function(a,b,c){switch(b){case "redirect":this.loadImg(a);break;
case "js":this.Script.loadInTag(a);break;case "iframe":b=document.createElement("iframe"),b.src=a,b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","display:none"),a=document.getElementById(c),a.parentNode.insertBefore(b,a)}},getBrowser:function(){try{var a=navigator.appName,b=navigator.userAgent,c,d=b.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);d&&null!==(c=b.match(/version\/([\.\d]+)/i))&&(d[2]=c[1]);return d=d?[d[1].toLowerCase(),parseFloat(d[2].match(/[\d]+[\.]*[\d]*/))]:
[a.toLowerCase(),navigator.appVersion,"-?"]}catch(e){return["",0]}},noAdAvailable:function(a,b,c,d,e,g){a=Ga(a,e,g);var f;A("e=unsoldPixel");1!==a.incomplete&&(Ea(a,c,d,e,g),a.unsoldTag?f=a.unsoldTag:c&&!document.getElementById(a.innerId)&&(f="<div style='display:inline;width:0px;height:0px;margin:0;padding:0' id='"+a.innerId+"'></div>"),f&&(f=Y(f,a),b?(document.write(ba(a,f)),aa(a)):this.iframedCode(a.innerId,f,a.w,a.h,a.iframedUnsold)),this.Refresh.lastAdAvailable(a),Admeta.Dispatcher.signalDone(),
a.unsoldMethod&&admetaEval(Y(a.unsoldMethod,a)))},unsold:function(a,b,c,d,e,g,f,h,l){z(p.Unsold,arguments);var k=Ga(a,h,l),q;k.unsoldTag||k.unsoldMethod||(Ea(k,g,f,h,l),void 0===e?b=unescape(b):(d=Admeta.MatC.generateId(),b=K(d,d,void 0,h,l,void 0)),c?(document.write(ba(k,b)),aa(k)):e?document.getElementById(k.innerId).innerHTML=b:(d=Admeta.MatC.generateId(),q=K(d,d,void 0,h,l,void 0),document.getElementById(k.innerId).innerHTML=q,Z(d,b)),e&&(document.getElementById(d).src=e),Fa(k,!0))},embedIfrCode:function(a){return"<!DOCTYPE html><html><body style='margin:0px;padding:0px;'>"+
a+"</body></html>"},Refresh:function(){function a(a){var b="Admeta.Refresh.tmHandler('"+a.gid+"')",c=a.timerStarted?1E3*a.RF:a.pollTimeOut;a.pollTimeOut=1E3;setTimeout(b,c)}function b(a,b){a.onmouseover=function(){var a=Admeta.MatC.getExisting(b);a&&(a.active=1)};a.onmouseout=function(){var a=Admeta.MatC.getExisting(b);a&&(a.active=0)}}function c(a){if(a.adsQueue.length>=a.maxAds){if(0<a.maxAds)switch(a.qPos=++a.qPos%a.maxAds,a=a.adsQueue[a.qPos],a.type){case "text":var b=Admeta.Text,c;b.init.apply(b,
a.init);for(c=0;c<a.ads.length;c++)b.create.apply(b,a.ads[c]);b.insert.apply(b,a.insert);break;case "image":Admeta.Image.insert.apply(Admeta.Image,a.ad);break;case "flash":Admeta.Flash.insert.apply(Admeta.Flash,a.ad);break;case "html":Admeta.JS.insert.apply(Admeta.JS,a.ad);break;case "dhtml":Admeta.JS.insertC.apply(Admeta.JS,a.ad)}}else window.ADM_PL=void 0,b=Admeta.setParams(Admeta.base+"JSAdservingMP.ashx?pc={pc}&pbId={pbId}&clk={clk}&exm={exm}&jsv={jsv}&tsv={tsv}&cts={cts}&arp={arp}&fl={fl}&vitp={vitp}&vit={vit}&jscb={jscb}&url={url}&fp={fp}&oid={oid}&exr={exr}&mraid={mraid}&apid={apid}&apbndl={apbndl}&mpp={mpp}&uid={uid}&cb={cb}",
[["pc",1],["arp",a.arp]]),b=U(b,void 0),b+=Admeta.setParams("&pId{o}={pId}&rank{o}={rank}&gid{o}={gid}&pp{o}={pp}&clk{o}={clk}&rpos{o}={rpos}&ecpm{o}={ecpm}&ntv{o}={ntv}&ntl{o}={ntl}&adsid{o}={adsid}",[["o",0],["pId",a.pid],["rank",a.o],["clk",a.clk||""],["gid",a.gid]]),Admeta.Script.load(b,!0,a.innerId+"_scr",1)}return{maxAds:2,setup:function(b){if(b)return b.RF&&0<b.RF&&a(b),b},attMaterial:function(a){b(document.getElementById(a.innerId),a.gid);a.arp++},lastAdAvailable:function(a){a.RF&&0!==a.RF&&
(a.maxAds=a.adsQueue.length,c(a))},tmHandler:function(b){b=Admeta.MatC.getExisting(b);if(Admeta.focus&&!b.active&&Admeta.MatC.checkElemVisible(b.innerId)){if(b.timerStarted){c(b);return}b.timerStarted=!0}a(b)}}}(),Flash:function(){function a(a,c,d,e,g,f,h,l,k){Admeta.Flash.support()?(e=g+"="+f,h&&(e+="&trackingcode="+escape(h)),l&&(e+="&retargetingtags="+escape(l)),h='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="'+G+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" id="vfmov" width="'+
c+'" height="'+d+'" align="middle" mId="'+k+'">\n',h=h+'<param name="allowScriptAccess" value="always">\n'+('<param name="movie" value="'+a+"?"+e+'">\n'),h+='<param name="quality" value="high">\n',h+='<param name="wmode" value="opaque">\n',h+='<embed src="'+a+"?"+e+'" width="'+c+'" height="'+d+'" quality=high name="vfmov" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="'+G+'www.macromedia.com/go/getflashplayer" wmode="opaque" outline="none"></embed>\n',
h+="</object>"):(e.match("pixel\\.gif$")&&(c=d="1px"),h='<a href="'+unescape(f)+'" target="_blank" rel="nofollow"><img src="'+e+'" width="'+c+'" height="'+d+'" border="0"></a>');return h}return{insert:function(b,c,d,e,g,f,h,l,k,q,r,y,t,B,u,m,v,x,ca,p,n){Admeta.MatC.addFlash(r,arguments);var w=Admeta.setupMaterial(b,c,d,r,q,y,t,g,f,B,u,m,v,p,n,-1),z=a(e,g,f,h,l,k,x,ca,d);Admeta.insertMaterial(w,z)},write:function(b,c,d,e,g,f,h,l,k,q,r,y,t,B,u,m,v,x,ca,p,n){Admeta.MatC.addFlash(r,arguments);var w=Admeta.setupMaterial(b,
c,d,r,q,y,t,g,f,B,u,m,v,p,n,-1);Admeta.writeMaterial(w,a(e,g,f,h,l,k,x,ca,d))},support:function(){try{var a=Admeta.getBrowser();if("chrome"===a[0]&&45<=a[1])return!1;var c,d;if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)for(c=navigator.plugins["Shockwave Flash"].description.split(" "),d=0;d<c.length;++d){if(!isNaN(parseInt(c[d],10))&&5<=c[d])return!0}else if("msie"===a[0])for(d=10;0<d;d--)try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+
d),!0}catch(e){}return!1}catch(e){return!1}}}}(),Image:function(){function a(a,c,d,e,g,f,h){return'<a href="'+e+'" target="_blank" rel="nofollow"><img id="AM'+g+"_"+f+'" src="'+a+'" width="'+c+'" height="'+d+'" border="0" mId="'+h+'"></a>'}return{insert:function(b,c,d,e,g,f,h,l,k,q,r,y,t,B,u,m,v,x){Admeta.MatC.addImage(k,arguments);var p=Admeta.setupMaterial(b,c,d,k,l,q,r,g,f,y,t,B,u,m,v,x);Admeta.insertMaterial(p,a(e,g,f,h,b,c,d))},write:function(b,c,d,e,g,f,h,l,k,q,r,y,t,B,u,m,v,x){Admeta.MatC.addImage(k,
arguments);var p=Admeta.setupMaterial(b,c,d,k,l,q,r,g,f,y,t,B,u,m,v,x);Admeta.writeMaterial(p,a(e,g,f,h,b,c,d))}}}(),JS:function(){function a(a,c){a=unescape(a);a=F(a,"{clickthrough0}",unescape(c));a=F(a,"{clickthrough1}",c);a=F(a,"{clickthrough2}",escape(c));a=F(a,"{clickthrough}",unescape(c));return a=ra(a)}return{insert:function(a,c,d,e,g,f,h,l,k,q,r,y,t,B,u,m){var v=e,x=arguments,p=Admeta.setupMaterial(a,c,d,l,h,k,q,g,f,r,y,t,B,u,m);Admeta.MatC.addHTML(p.gid,x);Admeta.outputMaterial(0,p,void 0,
!0,v,!1)},write:function(a,c,d,e,g,f,h,l,k,q,r,y,t,m,u,p){var v=e,x=arguments,w=Admeta.setupMaterial(a,c,d,l,h,k,q,g,f,r,y,t,m,u,p);Admeta.MatC.addHTML(w.gid,x);Admeta.outputMaterial(1,w,void 0,!0,v,!1)},insertC:function(b,c,d,e,g,f,h,l,k,q,r,y,t,m){var u=e,p=g,v=arguments,x=Admeta.setupMaterial(b,c,d,k,l,0,0,f,h,void 0,void 0,void 0,void 0,y,t,m);Admeta.MatC.addDHTML(x.gid,v);u=a(u,p);Admeta.outputMaterial(0,x,u,!0,void 0,!0)},writeC:function(b,c,d,e,g,f,h,l,k,q,r,y,t,m){var u=e,p=g,v=arguments,
x=Admeta.setupMaterial(b,c,d,k,l,0,0,f,h,void 0,void 0,void 0,void 0,y,t,m);Admeta.MatC.addDHTML(x.gid,v);u=a(u,p);Admeta.outputMaterial(1,x,u,!1,void 0,!0)}}}(),MatC:function(){return{pList:[],setup:function(a,b,c,d,e,g,f,h,l,k,q,r,y,t,m,p,w,v,x,z,A){var n=Admeta.MatC.getExisting(d),C=!1;if(ha()){x=!0;var E;a:{try{E="1"===localStorage.getItem("AdmetaShowAdLocations");break a}catch(D){}E=!1}E&&(C=!0)}n?(v=void 0!==v?v:n.protect,n.adId=c,n.SIV=e,void 0!==g&&void 0===n.RF&&(n.RF=g),void 0!==f&&void 0===
n.RF&&(n.eff=f),n.w=h,n.h=l,n.timerStarted=!1,n.pollTimeOut=1,n.pid=a,n.o=b,n.visitorState=k,n.sImg=void 0!==q?q:n.sImg,n.sImgUrl=void 0!==r?r:n.sImgUrl,n.sImgH=void 0!==y?y:n.sImgH,n.sPos=void 0!==t?t:n.sPos,n.protect=v,void 0!==x&&(n.embed=x),n.rtbAdvertiserIds=A):(E=v=void 0!==v?v:Admeta.protect,E=void 0!==E?E:Admeta.protect,n={pid:a,o:b,gid:d,adId:c,visibilityState:0,innerId:d,SIV:e,RF:g,active:0,eff:f,w:h,h:l,arp:0,sImg:q,sImgUrl:r,sImgH:y,sPos:t?t:0,unsoldTag:m,unsoldMethod:p,soldMethod:z,iframedUnsold:w,
visitorState:k,protect:E,embed:x,timerStarted:!1,pollTimeOut:1,rtbAdvertiserIds:A,adsQueue:[]},n.maxAds=Admeta.Refresh.maxAds,n.qPos=-1,Admeta.MatC.pList[Admeta.MatC.pList.length]=n);n.highlight=C;return n},full:function(a){return a?a.adsQueue.length>=Admeta.Refresh.maxAds:!0},addTextInit:function(a,b){var c=this.getExisting(a);c.adsQueue[c.adsQueue.length]={type:"text",init:b,ads:[]}},addTextAd:function(a,b){var c=this.getExisting(a),c=c.adsQueue[c.adsQueue.length-1].ads;c[c.length]=b},addTextInsert:function(a,
b){var c=this.getExisting(a);c.adsQueue[c.adsQueue.length-1].insert=b},addImage:function(a,b){this.addAd("image",a,b)},addFlash:function(a,b){this.addAd("flash",a,b)},addHTML:function(a,b){this.addAd("html",a,b)},addDHTML:function(a,b){this.addAd("dhtml",a,b)},addAd:function(a,b,c){b=this.getExisting(b);this.full(b)||(b.adsQueue[b.adsQueue.length]={type:a,ad:c})},getExisting:function(a){var b,c;for(b=0;b<this.pList.length;b++)if(c=this.pList[b],c.gid===a)return c},generateId:function(){return(16777216*
(1+Math.random())|0).toString(16).substring(1)},setInnerId:function(a){var b=a.gid;a.innerId=(b&&2<b.length&&"AM"===b.substr(0,2)?b:"AM_"+this.generateId())+"_SIV"},getBoundingRect:function(a){var b=0,c=0,d=document.documentElement.scrollTop||document.body.scrollTop,e=document.documentElement.scrollLeft||document.body.scrollLeft,g=a.offsetWidth,f=a.offsetHeight;if("function"===typeof a.getBoundingClientRect)return a=a.getBoundingClientRect(),{top:a.top,right:a.right,bottom:a.bottom,left:a.left};if(a.offsetParent){do{var h;
try{h=!a.offsetParent||a.currentStyle&&"relative"===a.currentStyle||window.getComputedStyle&&"relative"===document.defaultView.getComputedStyle(a,null).getPropertyValue("position")?!0:!1}catch(l){h=!0}if(h)break;b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}while(a)}c-=e;b-=d;return{top:b,right:c+g,bottom:b+f,left:c}},checkAreaVisible:function(a){if(w()===m.CrossDomainIframe)return!1;try{var b=-1!==navigator.userAgent.indexOf("Opera"),c="CSS1Compat"===document.compatMode,d=window.disableIframeCheck?
self:top.self,e=window.disableIframeCheck?document:top.document,g=b?d.innerHeight:c?e.documentElement.clientHeight:e.body.clientHeight,f=b?d.innerWidth:c?e.documentElement.clientWidth:e.body.clientWidth,h=a.right-a.left,l=a.bottom-a.top;a.right>f&&(h-=a.right-f);0>a.left&&(h+=a.left);a.bottom>g&&(l-=a.bottom-g);0>a.top&&(l+=a.top);0>h&&(h=0);0>l&&(l=0);return.5<h*l/((a.right-a.left)*(a.bottom-a.top))}catch(k){}return!1},checkElemVisible:function(a,b,c){var d,e;switch(w()){case m.CrossDomainIframe:return!1;
case m.SameDomainIframe:try{d=window.frameElement}catch(g){}break;default:d=document.getElementById(a)}if(!d)return!1;try{return e=this.getBoundingRect(d),void 0!==b&&void 0!==c&&(e.right=e.left+b,e.bottom=e.top+c),this.checkAreaVisible(e)}catch(g){return!1}},checkElemForcedAreaVisible:function(a,b,c){return this.checkElemVisible(a,b,c)}}}(),SIV:function(){function a(){var a="",b=[],c=0,d,e=Admeta.MatC,g,m=!1;for(d=0;d<e.pList.length;d++)g=e.pList[d],g.visibilityTimer&&(m=!0),g.visibilityState===
h.VisiblePastThreshold&&(g.visibilityState=h.VisibilityReported,"string"===typeof g.visitorState?b.push(g.visitorState):b=b.concat(g.visitorState));m||(clearInterval(l),l=void 0);if(0!==b.length){for(d=0;d<b.length;d++)a+="&ad2vps"+c+"="+b[d],c++;Admeta.loadImg(f+("?mc="+c+a)+"&rnd="+D())}}function b(){function b(a){a.visibilityTimer=setTimeout(function(){Admeta.MatC.checkElemForcedAreaVisible(a.innerId,a.w,a.h)&&(a.visibilityState=h.VisiblePastThreshold);a.visibilityTimer=void 0},1E3)}var c=Admeta.MatC,
d,f;if(!e){e=!0;for(d=0;d<c.pList.length;d++)(f=c.pList[d])&&f.SIV&&f.visibilityState!==h.VisibilityReported&&(c.checkElemForcedAreaVisible(f.innerId,f.w,f.h)?f.visibilityState===h.Hidden&&(f.visibilityState=h.Visible,b(f),l||(l=setInterval(a,1500))):(f.visibilityState=h.Hidden,f.visibilityTimer&&(clearTimeout(f.visibilityTimer),f.visibilityTimer=void 0)));e=!1}}function c(){d||(d=!0,Admeta.SIV.parentOnLoad=window.onload||function(){},Admeta.SIV.parentOnScroll=window.onscroll||function(){},Admeta.SIV.parentOnResize=
window.onresize||function(){},window.addEventListener?(window.addEventListener("load",b,!1),window.addEventListener("scroll",b,!1),window.addEventListener("resize",b,!1)):window.attachEvent?(document.attachEvent("onreadystatechange",function q(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",q),g=!0,b())}),document.documentElement.doScroll&&void 0===window.frameElement&&function r(){if(!g){try{document.documentElement.doScroll("left")}catch(a){setTimeout(r,0);return}g=
!0;b()}}(),window.attachEvent("onscroll",b),window.attachEvent("onresize",b)):(window.onload=function(){Admeta.SIV.parentOnLoad();b()},window.onscroll=function(){Admeta.SIV.parentOnScroll();b()},window.onresize=function(){Admeta.SIV.parentOnResize();b()}))}var d=!1,e=!1,g=!1,f,h={Hidden:0,Visible:1,VisiblePastThreshold:2,VisibilityReported:3},l=void 0;return{init:function(a){f=a},setup:function(a){a&&a.SIV&&c()},checkVisibility:function(){"complete"===document.readyState&&d&&b()}}}(),Text:function(){function a(a,
b){var g=Admeta.Text.AdGroup[Admeta.Text.AdGroup.length-1];g.Operation=a;g.placementDetails=b;var f;f=5<=b.length?b[4]:void 0;var h=b[0],l=Admeta.xRenderF,k;l?(k=l[h],l[h]=void 0,f=f&&l[f]?l[f]:k):f=l;g.xRenderF=f;g.js?(c=Admeta.defLoad||0===a,Admeta.Script.load(g.js,Admeta.defLoad||0===a,void 0,0)):Admeta.Text.loadTextAdsJs(a)}var b=!1,c=!1;return{AdGroup:[],init:function(){this.AdGroup.push({initArgs:arguments,Ads:[],xRenderF:void 0})},create:function(){this.AdGroup[this.AdGroup.length-1].Ads.push(arguments)},
insert:function(){Admeta.storeMaterial(arguments[2]);Admeta.storeRtbAdvertiser(arguments[9]);a(0,arguments)},write:function(){Admeta.storeMaterial(arguments[2]);Admeta.storeRtbAdvertiser(arguments[9]);a(1,arguments)},pushPlacement:function(a){document.write('<div id="'+a+'"></div>')},customRender:function(a,b,c){var f=this.AdGroup[this.AdGroup.length-1];f.js=a;f.rop=1;void 0===Admeta.xRenderF&&(Admeta.xRenderF={});Admeta.xRenderF[c]=b},resetCustomRender:function(a){Admeta.xRenderF&&(Admeta.xRenderF[a]=
void 0)},loadTextAdsJs:function(a){void 0===Admeta.Text.ProcessTextAds?b||(b=!0,z(p.Undef,"Loading textads.js."),Admeta.Script.load(Admeta.versionFile(Admeta.textAdsJS,Admeta.textVersion),Admeta.defLoad||0===a||void 0===a&&c,void 0,0)):Admeta.Text.ProcessTextAds()}}}(),Script:function(){var a=[],b=0;return{loaded:function(){try{Admeta.inFrontCall=!1;void 0!==window.AdmetaIframed&&parent.Admeta.loadNext(Admeta.adsServed);Admeta.processAsync();0<b&&b--;if(0===b&&0<a.length){var c=a.pop();Admeta.Script.load(c.url,
!0,c.id,1)}else Admeta.Dispatcher.signalDone();Admeta.SIV.checkVisibility()}catch(d){R(d,"Exception on Script.loaded")}},load:function(c,d,e,g){"complete"===document.readyState&&(d=!0);if(g&&d&&0<b)a.push({url:c,id:e});else try{g&&b++,c=Admeta.setParams(c,[["exm",void 0!==Admeta.adsServed?Admeta.adsServed.join(","):""],["exr",void 0!==Admeta.rtbAdvertisersServed?Admeta.rtbAdvertisersServed.join(","):""]]),d?(A("e=defload&p="+encodeURIComponent(c)),Admeta.Script.loadInTag(c,e)):(A("e=dwload&p="+encodeURIComponent(c)),
document.write("<script charset='utf-8' type='text/javascript' src='"+c+"'>\x3c/script>"))}catch(f){R(f,"Load fail: "+c),g&&b--}},loadInTag:function(a,b){var e=document.getElementsByTagName("script")[0],g=document.getElementsByTagName("body")[0],f=document.createElement("script");f.type="text/javascript";f.async=!0;b&&(f.id=b);f.src=a;"undefined"!==typeof e&&null!==e?e.parentNode.insertBefore(f,e):g.appendChild(f)}}}(),AdChoices:function(){function a(a){var b="right:0px;bottom:0px";1===c&&(b="left:0px;bottom:0px");
2===c&&(b="left:0px;top:0px");3===c&&(b="right:0px;top:0px");return"position:absolute;"+b+';z-index:101;border:0;padding:0;margin:0;font-size:0;background: transparent url("'+a+'") no-repeat right top;height:'+h+"px;overflow:hidden;left:auto;bottom:auto;cursor:pointer;"}var b=!1,c=0,d,e="",g=0,f=0,h=0,l="";return{init:function(a,m,r,p,t,w,u,z){b=a;c=m;d=r;e=p;f=t;g=w;h=u;l=z},showHide:function(a,b){document.getElementById(a).style.display="block";document.getElementById(b).style.display="none"},getCode:function(c){if(!b)return"";
var h="_c_"+c.gid,m="_e_"+c.gid,p="'Admeta.AdChoices.showHide(\""+h+'", "'+m+"\")'",t="'Admeta.AdChoices.showHide(\""+m+'", "'+h+"\")'";c.adChoicesIdCollapsed=h;c.adChoicesWidth=f;return"<a id='"+h+"' style='"+(a(d)+"width:"+f+"px;")+"' onmouseover="+t+" href='"+l+"' target='_blank'></a><a id='"+m+"' style='display:none;"+(a(e)+"width:"+g+"px;")+"' onmouseout="+p+" href='"+l+"' target='_blank'></a>"}}}(),Dispatcher:function(){function a(){top.Admeta||(top.Admeta={});top.Admeta.ParentDispatch||(top.Admeta.ParentDispatch=
{ifrInQueue:[],busy:!1});var a=top.Admeta.ParentDispatch;top.Admeta.ParentDispatch.nextInQueue=function(){0===a.ifrInQueue.length||a.busy||(a.ifrInQueue.shift(1).Admeta.Dispatcher.processImpressions(a.adsServed,a.rtbAdvertisersServed),a.busy=!0)};top.Admeta.ParentDispatch.setupCallback=function(b){a.ifrInQueue.push(b);1===a.ifrInQueue.length&&a.nextInQueue()};top.Admeta.ParentDispatch.loadNext=function(b,c){a.adsServed||(a.adsServed=[]);b&&N(a.adsServed,b);a.rtbAdvertisersServed||(a.rtbAdvertisersServed=
[]);c&&N(a.rtbAdvertisersServed,c);a.busy=!1;a.nextInQueue()}}var b=!1,c=!1;return{init:function(){if(w()===m.SameDomainIframe){try{a()}catch(c){return}b||(b=!0)}},processImpressions:function(a,b){window.ADM_PL={defLoad:!0};Admeta.adsServed=a;Admeta.rtbAdvertisersServed=b;J(!0)},delayImpression:function(){var a;(a=!window.ADM_PL||!b||"fp"===window.ADM_PL.tp||"fpc"===window.ADM_PL.tp)||(a=da(Pa)?!0:window.AdmetaDisableIfrHTO);if(a)return!1;var e;a:{try{e=top.Admeta.ParentDispatch.busy;break a}catch(g){}e=
!1}if(!e){try{top.Admeta.ParentDispatch.busy=!0}catch(g){}return!1}za();z(p.ReceiveRequestInFriendlyIframe,ADM_PL);Admeta.base=O(Admeta.base);switch(ADM_PL.tp){case "spt":case "fpt":H(ADM_PL.tagId);break;default:X()}window.ADM_PL=void 0;c=!1;try{top.Admeta.ParentDispatch.setupCallback(window)}catch(g){Admeta.Dispatcher.processImpressions(Admeta.adsServed,Admeta.rtbAdvertisersServed)}setTimeout(Admeta.Dispatcher.signalDone,8E3);return!0},signalDone:function(){try{w()===m.SameDomainIframe?c||top.Admeta.ParentDispatch.loadNext(Admeta.adsServed,
Admeta.rtbAdvertisersServed):window.disableIframeCheck&&top.Admeta.ParentDispatch&&(top.Admeta.ParentDispatch.busy=!1)}catch(a){}c=!0}}}()}}();Admeta.processImpressions();
