/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-07-07 16:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>ABC</title>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/lap1.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <nav id=\"mainNav\" class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand page-scroll\" href=\"Home.html\">ABC</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"phone.html\">Phones & Tablets</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"lap.html\">Laptops & Computers</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"cam.html\">Cameras</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"tv.html\">TV, Audio & Surveillance</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"vehicle.html\">Vehicle Electronics & GPS</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>           \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<br/><br/><br/><br/>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"header-content\">\r\n");
      out.write("            <div class=\"header-content-inner\" align=\"center\">\r\n");
      out.write("                <h1>Laptops & Computers</h1>\r\n");
      out.write("\t\t\t\t<h3></h3>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <h3></h3>\r\n");
      out.write("                <a href=\"#about\" class=\"btn btn-primary btn-xl page-scroll\">Find Out More</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("<br/><br/><br/><br/>\r\n");
      out.write("    <section class=\"bg-primary\" id=\"about\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2 text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading\">What We've got!</h2>\r\n");
      out.write("                    <hr class=\"light\">\r\n");
      out.write("                    <p class=\"text-faded\">We have got manymore offers and previlages for our customers<br>We serves technlogy on your hand!!</p>\r\n");
      out.write("                    <br/>\r\n");
      out.write("\t\t\t\t\t<a href=\"#portfolio\" class=\"page-scroll btn btn-default btn-xl sr-button\">Get Started!</a>\r\n");
      out.write("               <br/><br/><br/>\r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t<br/><br/><br/><br/><br/>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap1.jpg\" alt=\"\" height=\"75px\"><br/><br/>\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\">LKR 83 000</h4>\r\n");
      out.write("<h4><a href=\"#\">SNew Acer Ultrabook Laptop</a>\r\n");
      out.write("</h4>\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<p>\r\n");
      out.write("Inexpensive ultrabook. Light weight. Responsive multitouch trackpad. Two USB 3.0 ports. No confusing USB 2.0 ports. Full size HDMI port. 2.4GHz and 5GHz Wi-Fi.\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap1.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap2.jpe\" alt=\"\" height=\"75px\"><br/><br/><br/><br/>\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\">LKR 88 000</h4>\r\n");
      out.write("<h4><a href=\"#\">HP Z400 Computer PC </a>\r\n");
      out.write("</h4>\r\n");
      out.write("<p>\r\n");
      out.write(" Processor Speed:2.66GHz\tModel:Z400\r\n");
      out.write("Graphics Processing Type:Nvidia NVS 290\tMPN:\t\r\n");
      out.write("Z400\r\n");
      out.write("Memory:\t8GB\tOperating System:Windows 7\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap2.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap3.jpg\" alt=\"\">\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\">LKR 80 000</h4>\r\n");
      out.write("<h4><a href=\"#\">\r\n");
      out.write("HP ProBook 6570b Notebook</a>\r\n");
      out.write("</h4>\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<p>\r\n");
      out.write("512 MB, Core: 550 MHz, Memory: 800 MHz, GDDR3, 8.670.8.0 Microsoft Windows 7 Professional 32 Bit\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap3.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap4.jpg\" alt=\"\"><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\">LKR 124 000</h4>\r\n");
      out.write("<h4><a href=\"#\">HP Envy dv6-7202eg Notebook </a>\r\n");
      out.write("</h4>\r\n");
      out.write("<p>\r\n");
      out.write("2048 MB, Core: 175-797,3 MHz, Memory: 900 MHz, ForceWare 306.97, Optimus Intel Core i7-3630QM 2.4 GHz (Intel Core i7)\r\n");
      out.write("</p><br/><br/><br/><br/>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap4.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap5.jpeg\" alt=\"\">\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\"></h4>\r\n");
      out.write("<h4><a href=\"#\">DELL Inspiron 14-3452 Laptop</a>\r\n");
      out.write("</h4>\r\n");
      out.write("<p>\r\n");
      out.write("Intel Celeron N2840 2.16 GHz Processor\r\n");
      out.write("2 GB DDR3 RAM; 500 GB HDD\r\n");
      out.write("HDMI 1.4a, USB 3.0 (1), USB 2.0 (2), Kensington lock slot, Media Card Reader 3-in-1, headphone/mic\r\n");
      out.write("14 inch 1366 x 768 pixels LED-lit Screen\r\n");
      out.write("Windows 8.1; Free upgrade to Windows 10\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap5.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("<div class=\"thumbnail\">\r\n");
      out.write("<img src=\"images/lap6.jpeg\" alt=\"\"><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("<div class=\"caption\">\r\n");
      out.write("<h4 class=\"pull-right\"></h4>\r\n");
      out.write("<h4><a href=\"#\">\r\n");
      out.write("Lenovo i-SlimBook Laptop</a>\r\n");
      out.write("</h4>\r\n");
      out.write("<p>\r\n");
      out.write("The Lenovo 100S has a colorful, fingerprint-resistant shell, a great keyboard and excellent battery life.1.33GHz Intel Atom Z3735F\r\n");
      out.write("2048MB DDR3 SDRAM 1333MHz\r\n");
      out.write("</p><br/><br/><br/><br/>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ratings\">\r\n");
      out.write("<a href=\"lap6.html\" class=\"btn btn-primary\">Order Now</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <aside class=\"bg-dark\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("            <div class=\"call-to-action\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"contact\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2 text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading\">Get In Touch With Us!</h2>\r\n");
      out.write("                    <hr class=\"primary\">\r\n");
      out.write("                    <p>Start Your transaction with us?<br> Great! Contact us via phone or mail us!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-lg-offset-2 text-center\">\r\n");
      out.write("                    <i class=\"fa fa-phone fa-3x sr-contact\"></i>\r\n");
      out.write("                    <p>+94-11-2571871</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 text-center\">\r\n");
      out.write("                    <i class=\"fa fa-envelope-o fa-3x sr-contact\"></i>\r\n");
      out.write("                    <p><a href=\"#\">abccompany@gmail.com</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin JavaScript -->\r\n");
      out.write("    <script src=\"js/scrollreveal.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.fittext.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"js/creative.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
