_GPL.j(function(e,c,bb,F,m,y,ka,w,X,Ea,L,Db,Eb,C,O,f,cb,la,db,x,t,ac,u,Fb,Fa){function Ga(a,b,d){d=d||f;var l=!0;a&&e.each(a,function(c,e){return l=!!b.call(d,e,c,a)});return l}function Gb(a){var b=[];Ga(a,function(a){0>e.inArray(a,b,void 0)&&b.push(a);return!0});return b}function Ha(){}function Hb(a,b){return e(a).parents().is(b)}function Ib(a){return e(a).map(function(a,d){(a=d.parentNode)&&a.removeChild(d);return d}).toArray()}function Ia(a,b){function d(b){for(var d=a.split(".");b&&d.length;)b=
b[d.shift()];return b}if(a)return Hb(ma,h.body)||(ma=Ib('<iframe style="display:none;visibility:hidden"></iframe>')[0],h.body.appendChild(ma)),d(ma.contentWindow)||b||d(f)}function Ja(a){var b=(a=a||f.event)&&a.type;if(b&&(a.cancelBubble=!0,Ia("Event.prototype.stopImmediatePropagation",Ha).call(a),Ia("Event.prototype.stopPropagation",Ha).call(a),"beforeunload"!==b))return a.returnValue=!1,Ia("Event.prototype.preventDefault",Ha).call(a),!b}function Y(a){a=Ea.userAgent.match(Db(a+"[/ ](\\d+)","i"));
return(a&&a[1])|0}function Jb(a,b,d,l){var c=[];Ga(a,function(d,e){var f=b.call(this,d,e,a);(f!==O||l)&&c.push(f);return!0},d||f);return c}function Kb(a){a&&"object"===typeof a&&(a=e.extend.apply(e,arguments));return a}function v(a){var b={_:1E8*Math.random()|0},d="cdnstats-a.akamaihd.net/s.gif?";Ga(arguments,function(a){"string"===typeof a?d=a:Kb(b,"function"===typeof a?a(b):a);return!0});(new Image).src=w.protocol+"//"+d+Jb(b,function(a,b){if(null!==a&&a!==O)return y(String(b))+"="+y(String(a))}).join("&")}
function Lb(a,b){b=b||[];for(var d=0,c=Math.random(),e,f=0;f<b.length;f++)if(d+=b[f][1],c<d&&!e&&(e=b[f][0]),b[f][0]===a){e=a;break}return e||b[0][0]}function M(){return new m/1E3|0}function Z(){fa(h,la,Z);Mb(function(a,b,d){na=a;Ka=b;aa||(aa=!0,La=!1,Nb(),Ob(),Ma(),d&&e('<link rel="dns-prefetch" href="//'+d+'">').appendTo(h.getElementsByTagName("head")[0]||ba),oa=+new m,pa=e(f).scrollLeft(),qa=e(f).scrollTop(),z(h,la,eb),z(f,"scroll",fb),z(f,"unload",gb),hb=Eb(function(){36E5<+new m-oa&&(v({t:"p_inactive",
d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0}),ra(!1))},5E3))})}function Nb(){function a(a){var d=ib();B.attr({href:d,target:Na()}).prop("src",d+"&"+c.B64.decode("ZGlzY2xvc2U="));return Ja(a)}B||(B=e('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0.01;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>'),z(B[0],"mousedown",a),z(B[0],"mouseup",Ja),z(B[0],"click",q),a());sa()}function eb(a){ga=[a.pageX,a.pageY,pa,qa];oa=+new m;sa()}function fb(){pa=
e(f).scrollLeft();qa=e(f).scrollTop();oa=+new m;sa()}function ra(a){aa&&(aa=!1,bb(hb),F(Oa),B.remove(),Pb(),fa(h,la,eb),fa(h,"scroll",fb),fa(f,"unload",gb),Ka=na=O,P=Q="",Pa=!1,a||z(h,la,Z),C(Z,1E3*X(R,G)))}function z(a,b,d){if(f[cb]){var c=ta();try{return c.call(a,b,d,!0)}catch(e){a[cb](b,d,!0)}}else a.attachEvent("on"+b,d)}function Ob(){ha=!0;c.ah(H,q);ca||c.ah("keydown",q);if("2016042613_t"===I){c.ah("focus",q);ca&&c.ah("blur",q);try{var a=h.createElement("iframe");a.style.width="0px";a.style.height=
"0px";a.style.border="none";h.body.appendChild(a);a.contentWindow.focus();f.focus();h.body.removeChild(a)}catch(b){}Qa&&c.ah("keyup",q)}e("*").add(f).each(function(a,b){ua(b)||z(b,H,q)});jb||(jb=!0,e("*").add(f).each(function(a,b){ua(b)||(z(b,"mousedown",S),z(b,"mouseup",S),z(b,"click",S))}),c.ah&&(c.ah("mousedown",S),c.ah("mouseup",S),c.ah("click",S)));e("iframe").each(function(a,b){try{ua(b)||z(b.contentWindow,H,q)}catch(c){}})}function Qb(){if(Y("Chrome")){for(var a=0;a<Ea.plugins.length;a++)if("Widevine Content Decryption Module"===
Ea.plugins[a].name)return!1;return!0}return!1}function sa(){if(aa){B.is(ba.lastChild)||B.appendTo(h.body);50<new m-kb&&(kb=+new m,lb=e("*").filter(function(a,d){return d[mb]}));var a=!1;e.each(lb,function(b,d){return!(a=nb(d))});B.css("display",a?"none":"block");F(Oa);Oa=C(sa,50)}}function nb(a){a=e(a);var b=ga[0]+(pa-ga[2]),d=ga[1]+(qa-ga[3]),c=a.offset(),f=c.left,c=c.top;return b>=f&&b<=f+a.width()&&d>=c&&d<=c+a.height()}function Rb(a,b,d){J.parentNode&&ia||(ia=ob());if(b!==w.href&&d){var c=b,k=
a;F(Ra);Ra=C(function(){f.onbeforeunload=function(){};f.name=k;e("iframe").remove();w.href=c},300);b=w.href;a="_blank";T=!0}var g;if(Y("Edge"))g=ia(b,a);else if(g=ia("","1749"===p?a:"_blank"))"_blank"!==a&&(g.name=a),g.location.href=b;!d||g&&!g.closed||(T=!1,F(Ra));if(ca&&J)try{J.contentWindow.location.reload(),ia=J.contentWindow.open}catch(m){}return g}function Na(){var a="ld893_";Q&&(a+="_"+y(Q),P&&(a+=","+P),a+="_");return a+="_"+M()}function ib(){if(na){var a=na;k&&(a+="&fo=1");var b;e("a[href]").not(B).each(function(a,
c){nb(c)&&c.protocol.match(/^http/i)&&-1===c.href.indexOf(va)&&-1===c.href.indexOf(pb)&&(b=c.protocol+"//"+c.host+c.pathname+c.search+c.hash)});b&&(a+="&t="+y(b.substring(0,X(0,1500-a.length))));a+="&rt="+(+new m-qb);wa&&(a+="&data_tag="+y(wa));return a+=rb?"&data_sid="+y(rb):""}}function Sb(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];e("title").length&&(b=b.concat(a(e("title").text())));e('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var d=
e.trim(e(this).attr("content"));d&&d.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(d)))});b=e.trim(Gb(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," ")).split(",");return e.unique(b).join(",")}function xa(a,b,d){a=(a||w.href).substr(0,1500);var l=d!==O?d:Sb();a=a.replace(/:/g,"%3A");l=l.replace(/:/g,"%3A").substring(0,X(0,1500-a.length));d=c.getSubId?"&subid="+c.getSubId(ya):"";a=y(c.B64.encode(a+"::z-"+p+"-"+Sa+"::"+l));b="&cb="+(b||sb);b+="&data_fr="+(tb(E)?"false":"true");b+="&data_proto="+y(w.protocol);
b+="&ed=1";k&&(b+="&fo=1&data_fo=1");return c.proto+va+"/pops?c="+a+"&a=1&ch="+y(za)+d+b}function fa(a,b,d){if(f[db])a[db](b,d,!0);else a.detachEvent("on"+b,d)}function Pb(){ha=!1;c.rh(H,q);ca||c.rh("keydown",q);"2016042613_t"===I&&(c.rh("focus",q),ca&&c.rh("blur",q),Qa&&c.rh("keyup",q));e("*").add(f).off(H,q);e("iframe").each(function(a,b){try{e(b.contentWindow).off(H,q)}catch(d){}});bb(Tb)}function Ub(a){a=a||f.event||{};if(T)return!0;for(a=a.target||a.srcElement;a;){var b=ua(a);if(b)return La||
(v({t:"p_bo",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,reason:b,bf:k|0}),La=!0),!0;a=a.parentNode}return!1}function K(a,b){a=L(a,10);isNaN(a)&&(a=L(ka&&ka.getItem(b)||c.gc(b,10),10)||0);return a}function tb(a){return(new m(1E3*(a||0))).toDateString()===(new m).toDateString()}function Aa(){E|=0;r|=0;N|=0;var a=M(),b=r&&!tb(E);b&&(r=0,A.set(u,r));var d=!U||a-E>=R&&r<U,a=a-N>=G;return!n&&b||d&&a}function q(a){a=a||f.event;if(!Ub(a)){var b=-1<["mousedown","mouseup","click"].indexOf(a.type);if(!(-1<["keydown",
"keyup"].indexOf(a.type)&&a.metaKey)){var d,l=ha&&ub(),e=ib();l&&(c.log("Popping to: "+e),d=Rb(Na(),e,b));if(d&&!d.closed)return l={url:e,cid:Q,crid:P},ra(!0),vb(),v({t:"p_success",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0}),Ba&&F(Ba),Ca&&F(Ca),T=!0,Vb(d,l),b||ja(),S(a);d&&d.closed?Ca||(Ca=C(function(){v({t:"popclose",u:e,location:w.hostname,pid:p,guid:c.guid,tag:wa||"",bf:k|0})},1E3)):l?Ba||(Ba=C(function(){v({t:"popfail",u:e,location:w.hostname,pid:p,guid:c.guid,tag:wa||""})},1E3)):ja()}}}function Vb(a,
b){function d(){fa(f,"focus",d);var a=+new m-e;v({delay:a,t:"pop_f",cid:b.cid,crid:b.crid,u:b.url,location:w.hostname,zoneid:Sa,pid:p,guid:c.guid,bf:k|0})}function l(){if(!a||a.closed||!1!==a.closed){var d=+new m-e;v({delay:d,t:"pop_c",cid:b.cid,crid:b.crid,u:b.url,location:w.hostname,zoneid:Sa,pid:p,guid:c.guid,bf:k|0})}else C(l,50)}var e=+new m;l();z(f,"focus",d)}function ub(){if(A.swf){E=K(A.get(x),x);316808>Ta.score&&(r=K(A.get(u),u));var a=Ua(A.get(t));N=K(a[V],t)}return Aa()}function Ma(){!A.swf&&
aa&&A.get([x,u,t],function(a){a=a.v;E=K(a[x],x);316808>Ta.score&&(r=K(a[u],u));a=Ua(a[t]);N=K(a[V],t);C(Ma,1E3)})}function wb(a,b,d){A.set(a,d);d=M();ka&&ka.setItem(a,d);b=L(b,10);var c=new m;c.setSeconds(c.getSeconds()+b);h.cookie=a+"="+d+";expires="+c.toUTCString()+";path=/;domain="+V}function vb(a){var b=M();wb(x,R,b);A.set(Fb,b);E=b;A.set(u,++r);a=a||V;G&&wb(t,G,Da+(Da&&",")+a+":"+b)}function Ua(a){var b={},d=M(),c=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=a[e].split(":"),
g=L(f[1],10);d-g<G&&(b[f[0]]=g,c.push(f[0]+":"+g))}Da=c.join(",");A.set(t,Da)}return b}function da(a){return a||Aa()||n?k||a?"US"===g?44551:-1<["CA","GB","AU","FR","IT"].indexOf(g)?44178:43956:"US"===g?n?45300:46818:-1<["CA","GB","AU","FR","IT"].indexOf(g)?n?44402:45300:n?44104:44402:M()-(N|0)<G?Infinity:r>=U?"US"===g?149058:-1<["CA","GB","AU","FR","IT"].indexOf(g)?88620:59858:"US"===g?47432:-1<["CA","GB","AU","FR","IT"].indexOf(g)?46818:45300}function Wb(a){"US"===g?Va(a,47432,149058):-1<["CA","GB",
"AU","FR","IT"].indexOf(g)?Va(a,46818,88620):Va(a,45300,59858);return Aa()}function Va(a,b,c){a>=b&&(R=0,a>=c&&r>=U&&(r=X(0,U-1)))}function Mb(a){!function d(){A.get(["frt","_GPL_oo_z7b85",x,t,u,Fa],function(e){if(e.v.frt){if("1750"===p){var h=e.v._GPL_oo_z7b85|0;if(86400>M()-h)return}I||(I=e.v[Fa],I=Lb(I,[["2016042613_c",.4],["2016042613_t",.6]]),A.set(Fa,I));xb||(xb=!0,c.pc(function(){yb?yb=!1:ha||(Wa=!1,ra(),Z())}));f[sb]=function(c){Xb(c,a)};h=M();E=K(e.v[x],x);r=K(e.v[u],u);e=Ua(e.v[t]);N=K(e[V],
t);e=Aa();Xa&&r>=Xa||(e?(e=da(),Ya=+new m,c.insertJS(xa()+"&ms="+e+"&r="+h),v({t:"p_req",ms:e,d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0})):(e=da(),c.log("minScoreNeeded: "+e),Infinity>e&&!Wa&&!n?(Ya=+new m,c.insertJS(xa()+"&ms="+e+"&r="+h),v({t:"p_req",ms:e,d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0}),Wa=!0):ja(),k||(F(Za),Za=C(d,1E3*(5+X(h,E+R,N+G)-h)))))}})}()}function ta(){if(!ta.v){var a=h.createElement("iframe");try{ba.appendChild(a),ta.v=a.contentWindow.Element.prototype.addEventListener,
ba.removeChild(a)}catch(b){a&&ba.removeChild(a)}}return ta.v||Element.prototype.addEventListener}function ob(){J=h.createElement("iframe");J.style.display="none";J.style.visibility="hidden";ba.appendChild(J);return J.contentWindow.open}function S(a){T&&!$a&&($a=C(function(){$a=O;T=!1},100));a=a||f.event||{};return T||a.type&&a.type!==H&&ha?Ja(a):!0}function zb(a,b){var d="http://"+pb+"/click",d=a.uh?d+("?h="+y(a.uh)):d+("?c="+y(a.cid)),d=d+(c.getSubId?"&subid="+c.getSubId(ya):""),d=d+(I?"&data_test="+
y(I):""),d=d+("&data_fb="+(Qb()?"yes":"no")),d=d+("&data_rtt="+b)+("&data_proto="+y(w.protocol)),d=d+("&data_ic="+(Ab?"true":"false"));k&&(d+="&data_fo=1&fo=1");return d+="&data_ss="+(screen.availHeight|0)+"x"+(screen.availWidth|0)}function ja(){Pa||k||Xa||(Pa=!0,Yb?Zb():c.insertJS(c.proto+c.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"))}function Zb(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ").join(",")}var b=c.rs(12);c.ah("mousedown",function(d){var l=d.target||d.srcElement;
if(l&&e(l).is("h3 a:visible")){var h=l.getAttribute("data-href")||l.href;if(h&&!l[b]){l[b]=!0;l.setAttribute("target","_blank");var q=c.rs(12);f[q]=function(b){if(b){var d=L(b.score,10);if(d>=da(!0)){Q=b.cid;P=b.crid;b=zb(b,0);k&&(b+="&t="+y(w.href));v({t:"p_bid",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,score:d,bf:k|0});try{var r=c.gd(h.split("/")[2])}catch(z){}r=r||V;vb(r);f.onbeforeunload=function(){};f.name=Na();e("iframe").remove();c.log("Popping to: "+b);w.href=b}else ab(),k||(k=!0,x+="_bm",t+=
"_bm",u+="_bm",va="s.hnisdlmm.com",ub(),Ma(),c.insertJS(xa(h,q,a(l.innerText))+"&ms="+da(!0)+"&r="+ +new m))}};d=da(!0);c.insertJS(xa(h,q,a(l.innerText))+"&ms="+d+"&r="+ +new m);v({t:"p_req",ms:d,d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0})}}})}function ab(){v({t:"p_nobid",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0})}function gb(){v({t:"p_unload",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,score:Ka,bf:k|0})}function ua(a){if(a){if(a[mb])return"ot";if(e(a).hasClass("sgsefvhuedc"))return"fo"}}function Xb(a,
b){var d=+new m-Ya;P=Q="";if(ea&&ea.score){if(!a||L(a.score,10)<L(ea.score,10))a=ea;ea=O}a?(a.crid&&(P=a.crid),a.cid&&(Q=a.cid),a.url||(a.url=zb(a,d)),d=L(a.score,10),d>=da()&&Wb(d)?(qb=+new m,F(Za),F(Bb),Bb=C(function(){v({t:"p_expired",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,bf:k|0});ra(!0);Z()},6E5),Ta={score:d,now:+new m},b(a.url,d,a.domain),v({t:"p_bid",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid,score:d,bf:k|0})):(k||(c.item_vars.z7b85_b=a),ab(),k||ja())):(ab(),k||ja())}var ma,A=c.items.e6a00,h=f.document,
ba=h.body,$b=Y("chrome"),ca=Y("firefox"),Qa=Y("safari"),za=c.item_vars["22555_ch"]||c.item_vars.ch||"",R,E,N,W=c.dt(),W=W&&W.inherited&&W.inherited.t||[],n="x"===za||-1<W.indexOf("adult")||!W.length&&0<e('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;n&&(-1===W.indexOf("adult_block")?za="x":(za="x-issue",n=!1));var G,ya="z7b85",va=c.gsd&&c.gsd(ya)||"s.hklmm.com",pb="pt21na.com",aa=!1,hb,oa,ha=!1,V=c.gd(),Ka,na,qb=0,Ya=0,Bb,Da="",r=0,U,Ta={},Q="",P="",Za,Wa=!1,I,Ba,Ca,wa,H="click";if($b||Qa)H=
"mousedown";else if(ca||h.all||Y("trident"))H="mouseup";var Cb=c.zoneid(ya,!0).split("_"),Sa=Cb[0],p=""+(Cb[1]||c.vars.pid),g=c.vars.cid,rb=c.vars.systemid,sb=c.rs(20),Ra,Tb,Ab=function(){try{return f[(f.btoa||function(a){return a})(w.hostname+"::"+(new m).toDateString())]===w.protocol}catch(a){return!1}}(),$a,mb="91c4",xb=!1,yb=!0,J,ia=ob(),T=!1,jb=!1,k=0<e("#z7b85bm").length,Pa=!1,ea,Xa=X(c.vars.z7b85_mp|0,0),lb=[],ga=[0,0,0,0],B,kb=0,Oa,pa=0,qa=0,La=!1,Yb="google"===c.gd().split(".").shift();k&&
(c.ri("z7b85bm"),x+="_bm",t+="_bm",u+="_bm",va="s.hnisdlmm.com",ea=c.item_vars.z7b85_b)&&(c.item_vars.z7b85_b=O);"1797"===p&&"GB"===g||f.name.match(/^_odctxdsp/)||"facebook.com"===V||(Ab?v({t:"idlecrawler",d:c.gd(),xr:+n,cid:g,pid:p,guid:c.guid}):(n?(U=R=0,G=180,x+="_xr",t+="_xr",u+="_xr"):(R=360,U=7,G=360),Z()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,window.localStorage,location,Math.max,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove",
"removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");